apiVersion: v1
kind: Service
metadata:
  name: model2-headless
  labels:
    app: model2
spec:
  clusterIP: None
  selector:
    app: model2
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
