apiVersion: v1
kind: Service
metadata:
  name: model2-svc
  labels:
    app: model2
spec:
  selector:
    app: model2
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  type: ClusterIP
