apiVersion: v1
kind: Service
metadata:
  name: model1-svc
  labels:
    app: model1
spec:
  selector:
    app: model1
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  type: ClusterIP
